import React,{useEffect,useRef,useState} from "react";
import {EvidenceChart as BaseEvidenceChart,Filters,MetricCard,SegmentedControl,SectionHeader,useDataApp,useDashboardTabs} from "../../data-app-public.jsx";
import "./dashboard.css";
const tabs=[{id:"withdrawal",label:"01_T0/T7提现率"},{id:"fpd",label:"02_提现订单及FPD"}],filterIds=["credit_pass_date","credit_type","product","risk_level","platform","media"];
const sum=(a,f)=>a.reduce((n,r)=>n+Number(r[f]||0),0),ratio=(n,d)=>d?n/d:null,pct=v=>v==null?"—":`${(v*100).toFixed(1)}%`,num=v=>v==null?"—":Math.round(v).toLocaleString("en-US");
const sd=v=>/^\d{4}-\d{2}-\d{2}$/.test(v??"")?`${v.slice(5,7)}/${v.slice(8,10)}`:v,cd=v=>`${sd(v)}\u2060`;
function week(d){const x=new Date(`${d}T00:00:00Z`);x.setUTCDate(x.getUTCDate()-((x.getUTCDay()+6)%7));return x.toISOString().slice(0,10)}
function groups(rows,grain){const m=new Map();rows.forEach(r=>{const p=grain==="week"?week(r.credit_pass_date):r.credit_pass_date,a=m.get(p)??[];a.push(r);m.set(p,a)});return[...m].sort(([a],[b])=>a.localeCompare(b))}
function ws(a){const x={credit_pass_customer_cnt:sum(a,"credit_pass_customer_cnt"),t0_withdraw_numerator:sum(a,"t0_withdraw_numerator"),t0_withdraw_denominator:sum(a,"t0_withdraw_denominator"),t7_withdraw_numerator:sum(a,"t7_withdraw_numerator"),t7_withdraw_denominator:sum(a,"t7_withdraw_denominator"),un:sum(a,"t0_withdraw_utilization_numerator"),ud:sum(a,"t0_withdraw_utilization_denominator")},full=x.t7_withdraw_denominator===x.credit_pass_customer_cnt;return{...x,t7_withdraw_denominator:full?x.t7_withdraw_denominator:0,t0:ratio(x.t0_withdraw_numerator,x.t0_withdraw_denominator),t7:full?ratio(x.t7_withdraw_numerator,x.t7_withdraw_denominator):null,util:ratio(x.un,x.ud)}}
function fs(a){const names=["loan_order_cnt","loan_customer_cnt","loan_amt_sum","credit_limit_sum","fpd0_numerator","fpd0_denominator","fpd0_amt_numerator","fpd0_amt_denominator","fpd10_numerator","fpd10_denominator","fpd10_amt_numerator","fpd10_amt_denominator"],x=Object.fromEntries(names.map(f=>[f,sum(a,f)]));return{...x,fpd0Rate:ratio(x.fpd0_numerator,x.fpd0_denominator),fpd10Rate:ratio(x.fpd10_numerator,x.fpd10_denominator),fpd0AmountRate:ratio(x.fpd0_amt_numerator,x.fpd0_amt_denominator),fpd10AmountRate:ratio(x.fpd10_amt_numerator,x.fpd10_amt_denominator),util:ratio(x.loan_amt_sum,x.credit_limit_sum)}}
const periods=(r,g,s)=>groups(r,g).map(([p,a])=>({period:p,label:cd(p),...s(a)}));
const rateAliases={t0:"t0Rate",t7:"t7Rate",util:"utilizationRate",rate:"segmentRate",fa0:"fpd0AmountRate",fa3:"fpd3AmountRate",share:"segmentShare"};
function EvidenceChart({spec,rows,...props}){
  const alias=field=>rateAliases[field]??field;
  const displayField=field=>/(?:Rate|Share)$/.test(alias(field))?`${alias(field)} (%)`:alias(field);
  const rateFields=[spec?.y,...(spec?.fields??[])].filter(Boolean);
  const mappedRows=rows.map(row=>({...row,...Object.fromEntries(rateFields.map(field=>{
    const target=displayField(field),value=row[field];
    return [target,target.endsWith(" (%)")&&value!=null?Number(value)*100:value];
  }))}));
  const legendLabels=spec?.legend?.labels?Object.fromEntries(Object.entries(spec.legend.labels).map(([field,label])=>[displayField(field),label])):undefined;
  const uniquePeriods=new Set(mappedRows.map(row=>row[spec?.x])).size;
  const seriesCount=spec?.series?new Set(mappedRows.map(row=>row[spec.series])).size:(spec?.fields?.length??1);
  const showValues=spec?.showValues??(spec?.type==="line"&&seriesCount<=8);
  const isRateChart=rateFields.some(field=>displayField(field).endsWith(" (%)"));
  const mappedSpec={...spec,y:displayField(spec?.y),...(spec?.fields?{fields:spec.fields.map(displayField)}:{}),valueDecimals:1,valueSuffix:isRateChart?"%":spec?.valueSuffix,showValues,...(legendLabels?{legend:{...spec.legend,labels:legendLabels}}:{})};
  const frameRef=useRef(null);
  useEffect(()=>{
    if(!isRateChart||!frameRef.current)return;
    const fix=()=>{frameRef.current.querySelectorAll(".recharts-label-list text").forEach(node=>{
      const value=node.textContent?.trim();
      if(value&&/^-?\d+(?:\.\d+)?$/.test(value))node.textContent=`${value}%`;
      const y=Number(node.getAttribute("y"));
      if(Number.isFinite(y)&&y<24)node.setAttribute("y","24");
      const svg=node.closest("svg"),x=Number(node.getAttribute("x")),width=svg?.viewBox?.baseVal?.width||svg?.clientWidth||0;
      if(Number.isFinite(x)&&width){
        if(x<42)node.setAttribute("text-anchor","start");
        else if(x>width-42)node.setAttribute("text-anchor","end");
      }
    });};
    fix();
    const observer=new MutationObserver(fix);
    observer.observe(frameRef.current,{childList:true,subtree:true,characterData:true});
    return()=>observer.disconnect();
  },[isRateChart,mappedRows]);
  return <div ref={frameRef} className={isRateChart?"rate-chart-frame":"chart-frame"}><BaseEvidenceChart spec={mappedSpec} rows={mappedRows} {...props}/></div>;
}
function M({id,q,title,value,note,rows}){return <MetricCard variant="card" id={id} queryId={q} title={title} value={value} description={note} sourceRows={rows}/>}
function riskShares(rows,grain,field,days=30){const last=[...new Set(rows.map(r=>r.credit_pass_date))].sort().at(-1),d=new Date(`${last}T00:00:00Z`);d.setUTCDate(d.getUTCDate()-days+1);const recent=rows.filter(r=>r.credit_pass_date>=d.toISOString().slice(0,10)),risks=[...new Set(recent.map(r=>r.risk_level))].sort();return{risks,rows:groups(recent,grain).flatMap(([p,a])=>{const total=sum(a,field);return risks.map(risk=>({label:cd(p),risk,share:ratio(sum(a.filter(r=>r.risk_level===risk),field),total)??0}))})}}
function RiskNumberSummary({title,rows,field}){
  const total=sum(rows,field),ranked=[...new Set(rows.map(r=>r.risk_level))]
    .map(risk=>({risk,count:sum(rows.filter(r=>r.risk_level===risk),field)}))
    .filter(r=>r.count>0).sort((a,b)=>b.count-a.count||String(a.risk).localeCompare(String(b.risk))).slice(0,3);
  return <article className="risk-number-card" data-reviewed-rows="true"><h3>{title}</h3><p>当前筛选范围绝对人数；展示人数最多的3个风险等级。</p><div className="risk-number-grid"><div className="risk-total"><span>合计</span><strong>{num(total)}</strong><em>100%</em></div>{ranked.map(({risk,count})=><div key={risk}><span>{risk}</span><strong>{num(count)}</strong><em>{pct(ratio(count,total))}</em></div>)}</div></article>;
}
export function DashboardContent(){const{snapshot,queries,filters,setFilter,reviewedRows,chartProps}=useDataApp(),{activeTabId}=useDashboardTabs(tabs),tab=activeTabId==="fpd"?"fpd":"withdrawal",[grain,setGrain]=useState("day"),q=tab==="fpd"?"loan_fpd_monitor":"withdrawal_monitor",fields=tab==="fpd"?["credit_pass_date","loan_date","credit_type","product","risk_level","platform","media","loan_utilization_bucket"]:["credit_pass_date","credit_type","product","risk_level","platform","media","t0_utilization_bucket"],rows=reviewedRows(q,fields);return <><Filters sticky filters={snapshot.filters.filter(f=>filterIds.includes(f.id))} queries={queries} values={filters} onChange={setFilter} trailingControls={<SegmentedControl label="统计粒度" size="compact" value={grain} onChange={setGrain} options={[{value:"day",label:"按日"},{value:"week",label:"按周"}]}/>} /><header className="monitor-hero"><h1>{tab==="fpd"?"提现订单及FPD":"授信后提现转化"}</h1><p>{tab==="fpd"?"以全部正式放款订单为底池，金额采用 loan_amt。":"T7分母仅包含已满7×24小时的授信通过客户。"}</p></header>{rows.length?(tab==="fpd"?<Fpd2 rows={rows} grain={grain} cp={chartProps}/>:<Withdrawal rows={rows} grain={grain} cp={chartProps}/>):<p className="empty-state">当前筛选范围没有数据。</p>}</>}
function Withdrawal({rows,grain,cp}){
  const q="withdrawal_monitor",p=periods(rows,grain,ws),daily=periods(rows,"day",ws),latest=daily.at(-1),mature=daily.filter(x=>x.t7_withdraw_denominator>0).at(-1);
  const riskTrend=groups(rows,grain).flatMap(([d,a])=>[...new Set(a.map(r=>r.risk_level))].sort().map(r=>({label:cd(d),risk:r,t0:ws(a.filter(x=>x.risk_level===r)).t0})));
  const bucketRows=groups(rows,grain).flatMap(([d,a])=>{const base=a.filter(r=>r.t0_utilization_bucket&&r.t0_utilization_bucket!=="\\N"),total=sum(base,"t0_withdraw_numerator");return["01_100%以下","02_100%及以上"].map(b=>({label:cd(d),bucket:b.replace(/^\d+_/,""),share:ratio(sum(base.filter(r=>r.t0_utilization_bucket===b),"t0_withdraw_numerator"),total)??0}))});
  const credit=riskShares(rows,grain,"credit_pass_customer_cnt"),t0=riskShares(rows,grain,"t0_withdraw_numerator"),stack=(risks)=>({type:"stackedBar100",x:"label",y:"share",series:"risk",yLabel:"客户占比",legend:{labels:Object.fromEntries(risks.map(r=>[r,r]))}});
  return <>
    <section className="metric-grid"><M id="credit" q={q} title="昨日通过量" value={num(latest?.credit_pass_customer_cnt)} note={sd(latest?.period)} rows={rows}/><M id="t0" q={q} title="T0提现申请率" value={pct(latest?.t0)} note={`${num(latest?.t0_withdraw_numerator)} / ${num(latest?.t0_withdraw_denominator)}`} rows={rows}/><M id="t7" q={q} title="T7提现申请率" value={pct(mature?.t7)} note={`最新成熟日 ${sd(mature?.period)}`} rows={rows}/><M id="util" q={q} title="T0额度使用率" value={pct(latest?.util)} note="申请金额 / 授信额度" rows={rows}/></section>
    <section className="chart-grid"><EvidenceChart id="withdraw" queryId={q} title="T0 / T7提现申请率趋势" spec={{type:"line",x:"label",y:"t0",fields:["t0","t7"],yLabel:"提现申请率",legend:{labels:{t0:"T0提现申请率",t7:"T7提现申请率"}}}} rows={p} sourceRows={rows} height={300} {...cp("withdraw")}/><EvidenceChart id="util-trend" queryId={q} title="T0额度使用率趋势" spec={{type:"line",x:"label",y:"util",yLabel:"额度使用率"}} rows={p} sourceRows={rows} height={300} {...cp("util-trend")}/></section>
    <section className="distribution-section"><SectionHeader id="risk-head" title="客户风险等级分布"/><div className="chart-grid"><EvidenceChart id="credit-risk" queryId={q} title="授信通过客户风险等级分布" spec={stack(credit.risks)} rows={credit.rows} sourceRows={rows} height={300} {...cp("credit-risk")}/><EvidenceChart id="t0-risk" queryId={q} title="T0提现申请客户风险等级分布" spec={stack(t0.risks)} rows={t0.rows} sourceRows={rows} height={300} {...cp("t0-risk")}/></div><div className="chart-grid risk-number-summary-grid"><RiskNumberSummary title="授信通过客户风险等级绝对值汇总" rows={rows} field="credit_pass_customer_cnt"/><RiskNumberSummary title="T0提现申请客户风险等级绝对值汇总" rows={rows} field="t0_withdraw_numerator"/></div></section>
    <section className="chart-grid distribution-section"><EvidenceChart id="risk-t0-rate" queryId={q} title="各风险等级T0提现申请率" description="展示当前筛选下全部时间。" spec={{type:"line",x:"label",y:"t0",series:"risk",yLabel:"T0提现申请率"}} rows={riskTrend} sourceRows={rows} height={330} {...cp("risk-t0-rate")}/><EvidenceChart id="bucket-share" queryId={q} title="T0额度使用率分组占比" description="按时间展开，每期合计100%。" spec={{type:"stackedBar100",x:"label",y:"share",series:"bucket",yLabel:"客户占比"}} rows={bucketRows} sourceRows={rows} height={330} {...cp("bucket-share")}/></section>
  </>;
}
function Fpd({rows,grain,cp}){const q="loan_fpd_monitor",p=periods(rows,grain,fs),daily=periods(rows,"day",fs),last=daily.at(-1),f0=daily.filter(x=>x.fpd0_denominator>0).at(-1),f3=daily.filter(x=>x.fpd3_denominator>0).at(-1),line=(dim)=>groups(rows,grain).flatMap(([d,a])=>[...new Set(a.map(r=>r[dim]))].sort().map(v=>{const x=fs(a.filter(r=>r[dim]===v));return{label:cd(d),segment:String(v).replace(/^\d+_/,""),rate:x.f0,den:x.fpd0_denominator}})).filter(x=>x.den>0),risk=line("risk_level"),bucket=line("loan_utilization_bucket"),dist=riskShares(rows,grain,"fpd0_numerator");return <><section className="metric-grid metric-grid--four"><M id="loans" q={q} title="最新放款单量" value={num(last?.loan_order_cnt)} note={sd(last?.period)} rows={rows}/><M id="loan-util" q={q} title="放款额度使用率" value={pct(fs(rows).util)} note="放款总额 / 授信额度总额" rows={rows}/><M id="f0" q={q} title="FPD0订单逾期率" value={pct(f0?.f0)} note={`最新有效日 ${sd(f0?.period)}`} rows={rows}/><M id="f3" q={q} title="FPD3订单逾期率" value={pct(f3?.f3)} note={`最新有效日 ${sd(f3?.period)}`} rows={rows}/></section><section className="chart-grid"><EvidenceChart id="loan-trend" queryId={q} title="放款单量趋势" spec={{type:"line",x:"label",y:"loan_order_cnt",yLabel:"放款订单数"}} rows={p} sourceRows={rows} height={300} {...cp("loan-trend")}/><EvidenceChart id="fpd-order" queryId={q} title="FPD0 / FPD3订单逾期率趋势" spec={{type:"line",x:"label",y:"f0",fields:["f0","f3"],yLabel:"订单逾期率",legend:{labels:{f0:"FPD0",f3:"FPD3"}}}} rows={p} sourceRows={rows} height={300} {...cp("fpd-order")}/></section><section className="chart-grid distribution-section"><EvidenceChart id="fpd-risk-dist" queryId={q} title="FPD0逾期订单风险等级分布" description="近一个月，每期合计100%。" spec={{type:"stackedBar100",x:"label",y:"share",series:"risk",yLabel:"订单占比"}} rows={dist.rows} sourceRows={rows} height={310} {...cp("fpd-risk-dist")}/><EvidenceChart id="fpd-amount" queryId={q} title="FPD0 / FPD3金额逾期率趋势" spec={{type:"line",x:"label",y:"fa0",fields:["fa0","fa3"],yLabel:"金额逾期率",legend:{labels:{fa0:"FPD0",fa3:"FPD3"}}}} rows={p} sourceRows={rows} height={310} {...cp("fpd-amount")}/></section><section className="chart-grid distribution-section"><EvidenceChart id="fpd-risk-rate" queryId={q} title="各风险等级FPD0逾期率趋势" spec={{type:"line",x:"label",y:"rate",series:"segment",yLabel:"FPD0订单逾期率"}} rows={risk} sourceRows={rows} height={330} {...cp("fpd-risk-rate")}/><EvidenceChart id="fpd-bucket-rate" queryId={q} title="各额度使用率分桶FPD0逾期率趋势" spec={{type:"line",x:"label",y:"rate",series:"segment",yLabel:"FPD0订单逾期率"}} rows={bucket} sourceRows={rows} height={330} {...cp("fpd-bucket-rate")}/></section></>}

function Fpd2({rows,grain,cp}){
  const q="loan_fpd_monitor",all=periods(rows,grain,fs),daily=periods(rows,"day",fs),last=daily.at(-1);
  const matured=all.filter(x=>x.fpd0_denominator>0||x.fpd10_denominator>0),f0=daily.filter(x=>x.fpd0_denominator>0).at(-1),f10=daily.filter(x=>x.fpd10_denominator>0).at(-1);
  const segmentRows=dim=>groups(rows,grain).flatMap(([d,a])=>[...new Set(a.map(r=>r[dim]))].sort().map(v=>{const x=fs(a.filter(r=>r[dim]===v));return{label:cd(d),segment:String(v).replace(/^\d+_/,""),fpd0Rate:x.fpd0Rate,fpd0AmountRate:x.fpd0AmountRate,den:x.fpd0_denominator}})).filter(x=>x.den>0);
  return <><section className="metric-grid metric-grid--four"><M id="loans" q={q} title="最新放款单量" value={num(last?.loan_order_cnt)} note={sd(last?.period)} rows={rows}/><M id="loan-util" q={q} title="放款额度使用率" value={pct(fs(rows).util)} note="放款总额 / 授信额度总额" rows={rows}/><M id="f0" q={q} title="FPD0订单逾期率" value={pct(f0?.fpd0Rate)} note={`最新有效日 ${sd(f0?.period)}`} rows={rows}/><M id="f10" q={q} title="FPD10订单逾期率" value={pct(f10?.fpd10Rate)} note={`最新有效日 ${sd(f10?.period)}`} rows={rows}/></section>
  <section className="chart-grid"><EvidenceChart id="loan-trend" queryId={q} title="放款单量趋势" spec={{type:"line",x:"label",y:"loan_order_cnt",yLabel:"放款订单数"}} rows={all} sourceRows={rows} height={300} {...cp("loan-trend")}/><EvidenceChart id="fpd-order" queryId={q} title="FPD0 / FPD10订单逾期率趋势" description="未进入观察期的日期不展示。" spec={{type:"line",x:"label",y:"fpd0Rate",fields:["fpd0Rate","fpd10Rate"],yLabel:"订单逾期率",legend:{labels:{fpd0Rate:"FPD0",fpd10Rate:"FPD10"}}}} rows={matured} sourceRows={rows} height={300} {...cp("fpd-order")}/></section>
  <section className="distribution-section"><EvidenceChart id="fpd-amount" queryId={q} title="FPD0 / FPD10金额逾期率趋势" spec={{type:"line",x:"label",y:"fpd0AmountRate",fields:["fpd0AmountRate","fpd10AmountRate"],yLabel:"金额逾期率",legend:{labels:{fpd0AmountRate:"FPD0",fpd10AmountRate:"FPD10"}}}} rows={matured} sourceRows={rows} height={310} {...cp("fpd-amount")}/></section>
  <section className="chart-grid distribution-section"><EvidenceChart id="fpd-risk-rate" queryId={q} title="各风险等级FPD0逾期率趋势" spec={{type:"line",x:"label",y:"fpd0Rate",series:"segment",yLabel:"FPD0订单逾期率"}} rows={segmentRows("risk_level")} sourceRows={rows} height={330} {...cp("fpd-risk-rate")}/><EvidenceChart id="fpd-risk-amount-rate" queryId={q} title="各风险等级FPD0金额逾期率趋势" spec={{type:"line",x:"label",y:"fpd0AmountRate",series:"segment",yLabel:"FPD0金额逾期率"}} rows={segmentRows("risk_level")} sourceRows={rows} height={330} {...cp("fpd-risk-amount-rate")}/></section>
  <section className="chart-grid distribution-section"><EvidenceChart id="fpd-bucket-rate" queryId={q} title="各额度使用率分桶FPD0逾期率趋势" spec={{type:"line",x:"label",y:"fpd0Rate",series:"segment",yLabel:"FPD0订单逾期率"}} rows={segmentRows("loan_utilization_bucket")} sourceRows={rows} height={330} {...cp("fpd-bucket-rate")}/><EvidenceChart id="fpd-bucket-amount-rate" queryId={q} title="各额度使用率分桶FPD0金额逾期率趋势" spec={{type:"line",x:"label",y:"fpd0AmountRate",series:"segment",yLabel:"FPD0金额逾期率"}} rows={segmentRows("loan_utilization_bucket")} sourceRows={rows} height={330} {...cp("fpd-bucket-amount-rate")}/></section></>
}
